version: '3.8'

services:
  db:
    image: postgres:15
    container_name: teamflow-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: teamflow
    ports:
      - "5432:5432"
    volumes:
      - teamflow_data:/var/lib/postgresql/data

volumes:
  teamflow_data: